In [1]:
import pandas as pd
data = pd.Series([10,20,30,40])
print(data)

0    10
1    20
2    30
3    40
dtype: int64

In [3]:
import pandas as pd
data = {
    "Name":["Ram", "Vani"],
    "Age":[20,25]
}

df = pd.DataFrame(data)
print(df)
print("\n")

   Name  Age
0   Ram   20
1  Vani   25

In [4]:
df.isnull()

    Name    Age
0  False  False
1  False  False

In [8]:
data=pd.Series([10,20,30],index=["x","y","z"])
print(data)

x    10
y    20
z    30
dtype: int64

In [14]:
df=pd.read_csv("C:\\Users\\RVUW262\\Desktop\\Trial.csv")
print(df)

      Name: Class:  Marks:
0    Purvaj    Bca    67.0
1     Mohit    BBA     NaN
2  Shourrya    NSS    69.0

In [15]:
df.isnull()

   Name:  Class:  Marks:
0  False   False   False
1  False   False    True
2  False   False   False

In [16]:
df.dropna()

      Name: Class:  Marks:
0    Purvaj    Bca    67.0
2  Shourrya    NSS    69.0

In [17]:
df.fillna(0)

      Name: Class:  Marks:
0    Purvaj    Bca    67.0
1     Mohit    BBA     0.0
2  Shourrya    NSS    69.0

In [28]:
print(df["Marks:"].mean())
print(df["Marks:"].sum())
print(df["Marks:"].min())
print(df["Marks:"].max())
print(df["Marks:"].count())

68.0
136.0
67.0
69.0
2

In [1]:
df.shape
df.ndim
len(df)
df.index
print(df.columns)

NameError: name 'df' is not defined

In [32]:
import pandas as pd

data = {
    "ID": [1, 2, 3, 4],
    "Name": ["Charlie", "Alistor", "Angel", "Pentious"],
    "Marks": [88, 70, 32, 99]
}

df = pd.DataFrame(data)
df.to_csv("students.csv",index=False)

print("CSV file created successfully")

CSV file created successfully